In [2]:
import pandas as pd
import numpy as np
df = pd.read_csv('homeprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   area      6 non-null      int64  
 1   bedrooms  5 non-null      float64
 2   age       6 non-null      int64  
 3   price     6 non-null      int64  
dtypes: float64(1), int64(3)
memory usage: 324.0 bytes


In [6]:
df.describe()

area  bedrooms        age          price
count     6.000000   5.00000   6.000000       6.000000
mean   3416.666667   4.20000  16.500000  648333.333333
std     587.934237   1.30384   8.288546  109117.673484
min    2600.000000   3.00000   8.000000  550000.000000
25%    3050.000000   3.00000   9.750000  572500.000000
50%    3400.000000   4.00000  16.500000  602500.000000
75%    3900.000000   5.00000  19.500000  722500.000000
max    4100.000000   6.00000  30.000000  810000.000000

In [5]:
df.isnull().sum()

area        0
bedrooms    1
age         0
price       0
dtype: int64

In [11]:
df['bedrooms'].unique()

array([ 3.,  4., nan,  5.,  6.])

In [7]:
df.columns

Index(['area', 'bedrooms', 'age', 'price'], dtype='object')

In [12]:
df['bedrooms'].median()

4.0

In [13]:
df['age']

0    20
1    15
2    18
3    30
4     8
5     8
Name: age, dtype: int64

In [16]:
df['bedrooms']= df['bedrooms'].fillna(df.bedrooms.median())
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   area      6 non-null      int64  
 1   bedrooms  6 non-null      float64
 2   age       6 non-null      int64  
 3   price     6 non-null      int64  
dtypes: float64(1), int64(3)
memory usage: 324.0 bytes


In [18]:
X = df.drop(columns=['price'])
X

area  bedrooms  age
0  2600       3.0   20
1  3000       4.0   15
2  3200       4.0   18
3  3600       3.0   30
4  4000       5.0    8
5  4100       6.0    8

In [20]:
y=df['price']
y

0    550000
1    565000
2    610000
3    595000
4    760000
5    810000
Name: price, dtype: int64

In [22]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state=0)

In [23]:
x_train

area  bedrooms  age
1  3000       4.0   15
3  3600       3.0   30
0  2600       3.0   20
4  4000       5.0    8

In [24]:
x_test

area  bedrooms  age
5  4100       6.0    8
2  3200       4.0   18

In [25]:
y_train

1    565000
3    595000
0    550000
4    760000
Name: price, dtype: int64

In [26]:
x_train

area  bedrooms  age
1  3000       4.0   15
3  3600       3.0   30
0  2600       3.0   20
4  4000       5.0    8

In [27]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [28]:
model.fit(x_train,y_train)

LinearRegression()

In [29]:
y_pred = model.predict(x_test)
y_pred

array([608500., 554875.])

In [33]:
model.predict([[2500,4,5]])

C:\Users\hafee\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([638125.])

In [38]:
from sklearn.metrics import mean_squared_error, r2_score
print('MSE: ',mean_squared_error(y_test,y_pred))
print('R2 Score:',r2_score(y_test, y_pred))
print('RMSE:',np.sqrt(mean_squared_error(y_test,y_pred)))

MSE:  21820507812.499813
R2 Score: -1.1820507812499814
RMSE: 147717.66249335188
